"""Unsliced Bambu project export using a project generated by official Bambu Studio."""
from pathlib import Path
import json
import math
import zipfile
from xml.etree import ElementTree as ET

CORE = 'http://schemas.microsoft.com/3dmanufacturing/core/2015/02'
PROD = 'http://schemas.microsoft.com/3dmanufacturing/production/2015/06'
BBL = 'http://schemas.bambulab.com/package/2021'
TEMPLATE = Path(__file__).resolve().parents[1] / 'assets/p2s-0.4-pla-basic.3mf'


def export_bambu_project(mesh, destination, preview, recommended, printer=None,
                         nozzle_mm=0.4, filament='PLA', plate='Textured PEI Plate',
                         template_path=None):
    """Preserve template hardware settings; embed bounded process settings, no toolpaths."""
    from server import safe_apply_process_overrides, normalize_name, SAFE_PROCESS_KEYS
    from defusedxml import ElementTree as SafeET
    template = Path(template_path).expanduser().resolve() if template_path else TEMPLATE
    if not template.is_file() or template.stat().st_size > 50 * 1024 * 1024:
        raise ValueError('Provide a small unsliced single-object Bambu project template')
    with zipfile.ZipFile(template) as archive:
        if sum(i.file_size for i in archive.infolist()) > 100 * 1024 * 1024:
            raise ValueError('Project template exceeds unpacked size limit')
        config = json.loads(archive.read('Metadata/project_settings.config'))
        # Copy only the necessary native model structure, never old G-code, previews or data files.
        root = SafeET.fromstring(archive.read('3D/3dmodel.model'))
        settings = SafeET.fromstring(archive.read('Metadata/model_settings.config'))
        components = root.findall(f'.//{{{CORE}}}component')
        build = root.findall(f'{{{CORE}}}build/{{{CORE}}}item')
        if len(components) != 1 or len(build) != 1:
            raise ValueError('Template must contain exactly one object with one mesh part')
        part_path = components[0].get(f'{{{PROD}}}path', '').lstrip('/')
        if not part_path.startswith('3D/Objects/') or '..' in part_path:
            raise ValueError('Unsupported template mesh path')
        part = SafeET.fromstring(archive.read(part_path))
    actual_nozzle = float(config['nozzle_diameter'][0])
    printer_names = {normalize_name(config.get('printer_model', '')),
                     normalize_name(config.get('printer_settings_id', '')),
                     normalize_name(config.get('printer_model', '')).removeprefix('bambulab')}
    if printer and normalize_name(printer) not in printer_names:
        raise ValueError('Requested printer does not match template; supply a matching Bambu project template')
    if not math.isclose(nozzle_mm, actual_nozzle):
        raise ValueError('Requested nozzle does not match template; supply a matching Bambu project template')
    actual_filament = config.get('filament_settings_id', [''])[0]
    generic_pla = filament == 'PLA' and actual_filament.startswith('Bambu PLA Basic @')
    if not generic_pla and normalize_name(filament) not in {
            normalize_name(actual_filament), normalize_name(actual_filament.split(' @')[0]),
            normalize_name(actual_filament.split(' @')[0]).removeprefix('bambu')}:
        raise ValueError('Requested filament does not match template; supply a matching Bambu project template')
    if plate not in {'Textured PEI Plate', 'Smooth PEI Plate', 'Cool Plate', 'Engineering Plate', 'High Temp Plate'}:
        raise ValueError('Unsupported plate name')
    config = safe_apply_process_overrides(config, recommended)
    config['curr_bed_type'] = plate
    # Retain vendor machine, temperature and G-code settings without modification.
    xy = [tuple(map(float, v.split('x'))) for v in config['printable_area']]
    low = [min(p[i] for p in xy) for i in range(2)]
    high = [max(p[i] for p in xy) for i in range(2)]
    if any(mesh.extents[i] > high[i] - low[i] for i in range(2)) or mesh.extents[2] > float(config['printable_height']):
        raise ValueError('Model exceeds template printer build volume; scaling is never automatic')
    mesh = mesh.copy()
    mesh.apply_translation([-float(mesh.bounds[:, 0].mean()), -float(mesh.bounds[:, 1].mean()), -float(mesh.bounds[0, 2])])
    build[0].set('transform', '1 0 0 0 1 0 0 0 1 ' + ' '.join([
        str((low[0]+high[0])/2), str((low[1]+high[1])/2), '0']))
    components[0].set('transform', '1 0 0 0 1 0 0 0 1 0 0 0')
    # Strip personal/template listing metadata while keeping Bambu identification.
    for metadata in list(root.findall(f'{{{CORE}}}metadata')):
        if metadata.get('name') not in {'Application', 'BambuStudio:3mfVersion'}:
            root.remove(metadata)
    geometries = part.findall(f'.//{{{CORE}}}mesh')
    if len(geometries) != 1:
        raise ValueError('Template must contain exactly one triangle mesh')
    geometry = geometries[0]
    geometry.clear()
    vertices = ET.SubElement(geometry, f'{{{CORE}}}vertices')
    for row in mesh.vertices:
        ET.SubElement(vertices, f'{{{CORE}}}vertex', dict(zip(('x', 'y', 'z'), (format(float(v), '.17g') for v in row))))
    triangles = ET.SubElement(geometry, f'{{{CORE}}}triangles')
    for row in mesh.faces:
        ET.SubElement(triangles, f'{{{CORE}}}triangle', dict(zip(('v1', 'v2', 'v3'), (str(int(v)) for v in row))))
    for metadata in settings.findall('.//metadata'):
        key = metadata.get('key', '')
        if key == 'name': metadata.set('value', '3D Print model')
        if key.startswith('source_'): metadata.set('value', '0' if key != 'source_file' else 'printable_model.stl')
        if key == 'matrix': metadata.set('value', '1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1')
        if key == 'gcode_file': metadata.set('value', '')
        if 'face_count' in metadata.attrib: metadata.set('face_count', str(len(mesh.faces)))
    for stats in settings.findall('.//mesh_stat'):
        stats.set('face_count', str(len(mesh.faces)))
    from unsliced import REL, TYPES, xml_bytes
    ET.register_namespace('', CORE); ET.register_namespace('p', PROD); ET.register_namespace('BambuStudio', BBL)
    # Bambu declares required production extension by prefix; ensure it remains declared on each model.
    for model in (root, part):
        if not any(f'{{{PROD}}}' in str(key) for elem in model.iter() for key in elem.attrib):
            model.set('xmlns:p', PROD)
    types = ET.Element('Types', {'xmlns': TYPES})
    for ext, content in [('rels', 'application/vnd.openxmlformats-package.relationships+xml'),
                         ('model', 'application/vnd.ms-package.3dmanufacturing-3dmodel+xml'),
                         ('png', 'image/png'), ('config', 'application/octet-stream')]:
        ET.SubElement(types, 'Default', {'Extension': ext, 'ContentType': content})
    rels = ET.Element('Relationships', {'xmlns': REL})
    ET.SubElement(rels, 'Relationship', {'Id': 'rel0', 'Target': '/3D/3dmodel.model', 'Type': 'http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel'})
    ET.SubElement(rels, 'Relationship', {'Id': 'rel1', 'Target': '/Metadata/thumbnail.png', 'Type': 'http://schemas.openxmlformats.org/package/2006/relationships/metadata/thumbnail'})
    model_rels = ET.Element('Relationships', {'xmlns': REL})
    ET.SubElement(model_rels, 'Relationship', {'Id': 'rel0', 'Target': '/' + part_path, 'Type': 'http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel'})
    with zipfile.ZipFile(destination, 'w', zipfile.ZIP_DEFLATED) as archive:
        for path, data in {'[Content_Types].xml': xml_bytes(types), '_rels/.rels': xml_bytes(rels),
                           '3D/_rels/3dmodel.model.rels': xml_bytes(model_rels),
                           '3D/3dmodel.model': xml_bytes(root), part_path: xml_bytes(part),
                           'Metadata/model_settings.config': xml_bytes(settings),
                           'Metadata/project_settings.config': json.dumps(config, indent=2).encode()}.items():
            archive.writestr(path, data)
        archive.write(preview, 'Metadata/thumbnail.png')
    return {'printer_profile': config['printer_settings_id'], 'process_profile': config['print_settings_id'],
            'filament_profile': actual_filament, 'bambu_version': config['version'],
            'nozzle_mm': actual_nozzle, 'plate': plate,
            'settings_embedded': True, 'effective_settings': {k: config[k] for k in sorted(SAFE_PROCESS_KEYS) if k in config}}
